In [ ]:

import numpy as np
print(np.__version__)


2.1.3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[6,7,8]])
print(arr)

[[1 2 3]
 [6 7 8]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[6,7,8],[4,5,8]]])
print(arr)

[[[1 2 3]
  [6 7 8]
  [4 5 8]]]


In [ ]:
import numpy as np
arr=np.zeros((10,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.full((5,7),3)
print(arr)

[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[6.48770149e-316 0.00000000e+000 1.14428342e+243 8.03548366e-095
  7.18942963e+160]
 [1.89949265e-095 1.19654332e+180 4.63385214e+228 5.04431016e+180
  1.52553952e+247]
 [1.33907033e+199 1.50093842e+247 1.96925782e+243 9.44622326e+218
  5.04431016e+180]
 [1.52553952e+247 5.76148218e+160 5.42982163e+045 8.42959463e+252
  1.06505581e+094]
 [1.50093842e+247 1.57430883e+161 5.78027868e+074 5.50410564e-095
  5.49823181e+247]]


In [ ]:
import numpy as np
arr=np.eye((5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
import numpy as np
Even=np.arange(2,200,2)
print(Even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [ ]:
import numpy as np
Odd=np.arange(1,200,2)
print(Odd)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]


In [ ]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.33407144 0.22377485 0.32382165 0.86473385 0.25810603 0.18957212
 0.43172351 0.78966899 0.53322219 0.36857993]


In [ ]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[-1.08810963  0.63585687  0.18529042  0.12015297  0.69580262 -0.55736182
  0.84147338 -1.50564757  0.52470274  0.57921636]


In [ ]:
import numpy as np
arr=np.random.randint(10)
print(arr)

3


In [ ]:
import numpy as np
colour=["Black","white","red","orange","pink","Green"]
print(np.random.choice(colour,3))

['red' 'red' 'red']


In [ ]:
#copy
import numpy as np
arr=np.array([1,2,3,4,5])
new=arr.copy()
new[0]=42
print(arr)
print(new)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
#view()
import numpy as np
arr=np.array([1,2,3,4,5])
new=arr.view()
new[1]=42
print(arr)
print(new)

[ 1 42  3  4  5]
[ 1 42  3  4  5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])

arr+=10
print("Updated array value is",arr)

Updated array value is [11 12 13 14 15]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.add(A,B)
print(C)


[ 8 10 12 14 16 18]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.multiply(A,B)
print(C)

[ 7 16 27 40 55 72]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.subtract(A,B)
print(C)

[-6 -6 -6 -6 -6 -6]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5,6])
B=np.array([7,8,9,10,11,12])
C=np.divide(A,B)
print(C)

[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
C=np.dot(A,B)
print(C)

130


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(sum(arr))

55


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(min(arr))

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(max(arr))

10


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.std(arr))

2.8722813232690143


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(arr))

5.5


In [ ]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(arr))

[  1   3   4   4   7   8   9   9  11  34 141]


In [ ]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34,1,1,1,1,2,3,4,5,6,7,8])
print(np.unique(arr))

[  1   2   3   4   5   6   7   8   9  11  34 141]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)

(9,)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.size)

9


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.itemsize)

8


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.ndim)

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ndim)

2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])

2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1])

6


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[:,1])

[2 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,7,8,9,0,12,45,67])
print("original array is",arr)
new=arr.reshape(4,4)
print("Reshaped array is",new)


original array is [ 1  2  3  4  5  6  7  8  9  7  8  9  0 12 45 67]
Reshaped array is [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  7  8  9]
 [ 0 12 45 67]]
